# Copyright 2021 The Grin Developers and The BMW Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

trigger:
  branches:
    include:
      - master
  tags:
    include: ['*']

pr:
  branches:
    include: ['*']

variables:
  RUST_BACKTRACE: '1'
  RUSTFLAGS: '-C debug-assertions'

jobs:
- job: linux
  pool:
    vmImage: ubuntu-18.04
  strategy:
    matrix:
      test:
        CI_JOB: test-all
      release:
        CI_JOB: release
        PLATFORM: linux-amd64
  steps:
    - script: |
        sudo apt-get update -yqq
        sudo apt-get install -yqq --no-install-recommends libncursesw5-dev tor
      displayName: Linux Install Dependencies
    - template: '.ci/test.yml'
    - template: '.ci/release.yml'
- job: macos
  pool:
    vmImage: macos-latest
  strategy:
    matrix:
      test:
        CI_JOB: test-all
      release:
        CI_JOB: release
        PLATFORM: macos
  steps:
    - script: |
        brew uninstall llvm
        brew install tor
      displayName: macOS Uninstall LLVM
    - template: '.ci/test.yml'
    - template: '.ci/release.yml'
- job: windows
  pool:
    vmImage: windows-latest
  strategy:
    matrix:
      test:
        CI_JOB: test-all
      release:
        CI_JOB: release
        PLATFORM: win-x32
  steps:
    - script: |
        choco install -y llvm
        choco install -y tor
      displayName: Windows Install Dependencies
    - template: '.ci/test.yml'
    - template: '.ci/windows-release.yml'
- job: tarpaulin
  pool:
    vmImage: ubuntu-18.04
  strategy:
    matrix:
      coverage:
        CI_JOB: test-all
  steps:
    - script: |
        sudo apt-get update -yqq
        sudo apt-get install -yqq --no-install-recommends libncursesw5-dev libssl-dev sshpass tor
        cargo install cargo-tarpaulin
        cargo tarpaulin --all > tarpaulin.out.`date +"%s"`.txt
        sshpass -p "$(upload_pw)" ssh -o StrictHostKeyChecking=no uploader@bitcoinmw.com "mkdir -p /var/www/html/ci_uploads/rust-tor/`date +"%Y_%m_%d"`"
        sshpass -p "$(upload_pw)" scp -o StrictHostKeyChecking=no tarpaulin.*.txt uploader@bitcoinmw.com:/var/www/html/ci_uploads/rust-tor/`date +"%Y_%m_%d"`
      displayName: Code Coverage
