name: tor
author: The BMW Developers

args:
    - config:
        help: The configuration file for Tor
        short: c
        long: config
        value_name: FILE
        takes_value: true
    - debug:
        help: Whether to print debugging information
        short: d
        long: debug
        takes_value: false
